countries = [
{'cities': ['Andorra'], 'code': 'AD', 'continent': 'Europe', 'region': 'South', 'country': 'Andorra', 'capital': 'Andorra la Vella'},
{'cities': ['Tirane'], 'code': 'AL', 'continent': 'Europe', 'region': 'South', 'country': 'Albania', 'capital': 'Tirana'},
{'cities': ['Vienna'], 'code': 'AT', 'continent': 'Europe', 'region': 'West', 'country': 'Austria', 'capital': 'Vienna'},
{'cities': ['Brussels'], 'code': 'BE', 'continent': 'Europe', 'region': 'West', 'country': 'Belgium', 'capital': 'Brussels'},
{'cities': ['Sofia'], 'code': 'BG', 'continent': 'Europe', 'region': 'East', 'country': 'Bulgaria', 'capital': 'Sofia'},
{'cities': ['Minsk'], 'code': 'BY', 'continent': 'Europe', 'region': 'East', 'country': 'Belarus', 'capital': 'Minsk'},
{'cities': ['Prague'], 'code': 'CZ', 'continent': 'Europe', 'region': 'East', 'country': 'Czech Republic', 'capital': 'Prague'},
{'cities': ['Berlin', 'Hamburg', 'Munich'], 'code': 'DE', 'continent': 'Europe', 'region': 'West', 'country': 'Germany', 'capital': 'Berlin'},
{'cities': ['Copenhagen'], 'code': 'DK', 'continent': 'Europe', 'region': 'North', 'country': 'Denmark', 'capital': 'Copenhagen'},
{'cities': ['Tallinn'], 'code': 'EE', 'continent': 'Europe', 'region': 'North', 'country': 'Estonia', 'capital': 'Tallinn'},
{'cities': ['Helsinki'], 'code': 'FI', 'continent': 'Europe', 'region': 'North', 'country': 'Finland', 'capital': 'Helsinki'},
{'cities': ['Paris', 'Lyon'], 'code': 'FR', 'continent': 'Europe', 'region': 'West', 'country': 'France', 'capital': 'Paris'},
{'cities': ['Athens'], 'code': 'GR', 'continent': 'Europe', 'region': 'South', 'country': 'Greece', 'capital': 'Athens'},
{'cities': ['Budapest'], 'code': 'HU', 'continent': 'Europe', 'region': 'East', 'country': 'Hungary', 'capital': 'Budapest'},
{'cities': ['Dublin'], 'code': 'IE', 'continent': 'Europe', 'region': 'North', 'country': 'Republic of Ireland', 'capital': 'Dublin'},
{'cities': ['Rome', 'Milan'], 'code': 'IT', 'continent': 'Europe', 'region': 'South', 'country': 'Italy', 'capital': 'Rome'},
{'cities': ['Vaduz'], 'code': 'LI', 'continent': 'Europe', 'region': 'West', 'country': 'Liechtenstein', 'capital': 'Vaduz'},
{'cities': ['Vilnius'], 'code': 'LT', 'continent': 'Europe', 'region': 'North', 'country': 'Lithuania', 'capital': 'Vilnius'},
{'cities': ['Luxembourg'], 'code': 'LU', 'continent': 'Europe', 'region': 'West', 'country': 'Luxembourg', 'capital': 'Luxembourg'},
{'cities': ['Riga'], 'code': 'LV', 'continent': 'Europe', 'region': 'North', 'country': 'Latvia', 'capital': 'Riga'},
{'cities': ['Skopje'], 'code': 'MK', 'continent': 'Europe', 'region': 'South', 'country': 'Macedonia', 'capital': 'Skopje'},
{'cities': ['Valletta'], 'code': 'MT', 'continent': 'Europe', 'region': 'South', 'country': 'Malta', 'capital': 'Valletta'},
{'cities': ['Amsterdam'], 'code': 'NL', 'continent': 'Europe', 'region': 'West', 'country': 'Kingdom of the Netherlands', 'capital': 'Amsterdam'},
{'cities': ['Oslo'], 'code': 'NO', 'continent': 'Europe', 'region': 'North', 'country': 'Norway', 'capital': 'Oslo'},
{'cities': ['Warsaw', 'Krakow'], 'code': 'PL', 'continent': 'Europe', 'region': 'East', 'country': 'Poland', 'capital': 'Warsaw'},
{'cities': ['Lisbon', 'Oporto', 'Madeira', 'Azores'], 'code': 'PT', 'continent': 'Europe', 'region': 'South', 'country': 'Portugal', 'capital': 'Lisbon'},
{'cities': ['Bucharest'], 'code': 'RO', 'continent': 'Europe', 'region': 'East', 'country': 'Romania', 'capital': 'Bucharest'},
{'cities': ['Kaliningrad', 'Moscow', 'Volgograd', 'Samara', 'Yekaterinburg', 'Omsk', 'Novosibirsk', 'Krasnoyarsk', 'Irkutsk', 'Yakutsk', 'Vladivostok', 'Sakhalin', 'Magadan', 'Kamchatka', 'Anadyr'], 'code': 'RU', 'continent': 'Europe', 'region': 'East', 'country': 'Russia', 'capital': 'Moscow'},
{'cities': ['Stockholm'], 'code': 'SE', 'continent': 'Europe', 'region': 'North', 'country': 'Sweden', 'capital': 'Stockholm'},
{'cities': ['Ljubljana'], 'code': 'SI', 'continent': 'Europe', 'region': 'South', 'country': 'Slovenia', 'capital': 'Ljubljana'},
{'cities': ['Bratislava'], 'code': 'SK', 'continent': 'Europe', 'region': 'East', 'country': 'Slovakia', 'capital': 'Bratislava'},
{'cities': ['San_Marino'], 'code': 'SM', 'continent': 'Europe', 'region': 'South', 'country': 'San Marino', 'capital': 'San Marino'},
{'cities': ['Istanbul'], 'code': 'TR', 'continent': 'Asia', 'region': 'South', 'country': 'Turkey', 'capital': 'Ankara'},
{'cities': ['Kiev', 'Uzhgorod', 'Zaporozhye'], 'code': 'UA', 'continent': 'Europe', 'region': 'East', 'country': 'Ukraine', 'capital': 'Kiev'},
{'cities': ['Vatican'], 'code': 'VA', 'continent': 'Europe', 'region': 'South', 'country': 'Vatican City', 'capital': 'Vatican City'},
{'cities': ['Sarajevo'], 'code': 'BA', 'continent': 'Europe', 'region': 'South', 'country': 'Bosnia and Herzegovina', 'capital': 'Sarajevo'},
{'cities': ['Zagreb'], 'code': 'HR', 'continent': 'Europe', 'region': 'South', 'country': 'Croatia', 'capital': 'Zagreb'},
{'cities': ['Chisinau'], 'code': 'MD', 'continent': 'Europe', 'region': 'East', 'country': 'Moldova', 'capital': 'Chisinau'},
{'cities': ['Monaco'], 'code': 'MC', 'continent': 'Europe', 'region': 'West', 'country': 'Monaco', 'capital': 'Monaco'},
{'cities': ['Podgorica'], 'code': 'ME', 'continent': 'Europe', 'region': 'South', 'country': 'Montenegro', 'capital': 'Podgorica'},
{'cities': ['Belgrade'], 'code': 'RS', 'continent': 'Europe', 'region': 'South', 'country': 'Serbia', 'capital': 'Belgrade'},
{'cities': ['Madrid', 'Barcelona', 'Ceuta', 'Canary'], 'code': 'ES', 'continent': 'Europe', 'region': 'South', 'country': 'Spain', 'capital': 'Madrid'},
{'cities': ['Zurich', 'Geneva', 'Bern'], 'code': 'CH', 'continent': 'Europe', 'region': 'West', 'country': 'Switzerland', 'capital': 'Bern'},
{'cities': ['London', 'Edinburgh'], 'code': 'GB', 'continent': 'Europe', 'region': 'North', 'country': 'United Kingdom', 'capital': 'London'},
{'cities': ['Reykjavik'], 'code': 'IL', 'continent': 'Europe', 'region': 'North', 'country': 'Iceland', 'capital': 'Reykjavik'}
]
